GET http://localhost:6622/user/








###

GET http://localhost:6622/user/632e13bc7b2fdfd8f28a1bdd









###

POST http://localhost:6622/user
Content-Type: application/json

{
    "fullname":"Baisakhi Nandy",
    "mobile":"23131234",
    "email":"baisakhi.622@gmail.com",
    "ssn":"12312271",
    "desig":"manager",
    "uid":"hsdgaugq23843249",
    "empBranch":"3",
    "projid":""
}


###


PATCH  http://localhost:6622/user/632e13bc7b2fdfd8f28a1bdd
Content-Type: application/json

{
    "projid":""
}









###

GET http://localhost:6622/branchoffice



###

POST http://localhost:6622/branchoffice
Content-Type: application/json

{
    "branchname":"Port Lavaca",
    "address":"126 N. Nueces St. Port Lavaca, TX 77979"
}

###

GET http://localhost:6622/branchoffice/632e0e01fde62f5bbe7ac7fe

###
#todo
GET http://localhost:6622/branchoffice/branchlist


###

POST http://localhost:6622/consumeables
Content-Type: application/json

{
    "name":"RT Source",
    "stockQnt":"10",
    "dispatchQnt":"0",
    "desc":""
}


###

GET http://localhost:6622/consumeables




###

GET http://localhost:6622/consumeables/632eaaad8338b0c811324d5c



###

POST http://localhost:6622/equipements
Content-Type: application/json

{
    "name":"Film",
    "availableQnt":"100",
    "dispatchQnt":"20",
    "branchID":"aakjsdbakjsd0"
}

###

GET http://localhost:6622/equipements



