const mongoos=require("mongoose")

const userSchema= new mongoos.Schema({
    fullname:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    ssn:{  
        type:String,
        required:true
    },
    desig:{
        type:String,
        required:true
    },
    desigcatagory:{
        type:String,
        required:false
    },
    projid:{
        type:String,
        required:false
    },
    payrate_ST:{
        type:mongoos.Types.Decimal128,
        required:false
    },
    salary:{
        type:mongoos.Types.Decimal128,
        required:false
    },
    empBranch:{
        type:String,
        required:true
    },
    active:{
        type:Boolean,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    nPlusOne:{
        type:String,
        required:false
    },
    onBoardingDate:{
        type:String,
        required:false
    },
    Status:{
        type:String,
        required:false
    },
    StatusBg:{
        type:String,
        required:false
    }
})

module.exports=mongoos.model('User',userSchema )